Feat/chandlier
ApericotStudio/Poltergeist pull request #143
Opened 2023-11-29 13:56 UTC by hassanmohamed2003

2023-12-04 11:48 UTC, SirCodeye requested changes
Code looks good but the way drop works should be changed to a different approach as the spring joint is very buggy.

2023-12-06 15:22 UTC, dcsmit requested changes
Looks good but still needs one change

2023-12-06 15:22 UTC, dcsmit commented on Assets/Scripts/Interactable/Interactions/Drop.cs
> +    public GameObject connectedBody;
This variable should be private

2023-12-06 15:22 UTC, hassanmohamed2003 commented on Assets/Scripts/Interactable/Interactions/Drop.cs
> +    public GameObject connectedBody;
you are right

2023-12-06 15:28 UTC, SirCodeye approved these changes
Looks good! Approved

2023-12-06 15:32 UTC, merged