Feat/controller support menu
ApericotStudio/Poltergeist pull request #485
Opened 2024-01-16 11:25 UTC by hassanmohamed2003

## Description
Able to navigate menus with controller

## Setting up testing environment
1. In the project window navigate to Project/Assets/Scenes/UI and open the "MainMenuUI" and "Final Exam" scene.
2. Press Play.

## Fix Review
#### Controller support
Criteria:
- [ ] Able to complete tutorial and skip tutorial text by pressing control
- [ ] Able to go to pause screen by pressing select and navigate
- [ ] Able to navigate main menu

## Checklist
_These checks should always be true for your pull request_
- [x] My pull request is for one story/feature.
- [x] Every individual commit in this pull request is logical.
- [x] All code, documentation, commits and player seen texts are in English.
- [x] I have deleted unused / unnecessary code.
- [x] If my edits need a change in documentation, then I have updated the documentation.
- [x] All code is in correspondence with the code conventions.

2024-01-17 10:42 UTC, KiwiLT requested changes
pause menu doesn't seem to work for me, can you check with me what's happening?

2024-01-17 10:42 UTC, KiwiLT commented on Assets/Scripts/Game/GameManager.cs
You can directly trigger TogglePause from the OnOptionsInput event, no need for an extra function

2024-01-18 11:22 UTC, ThijsvanDijk commented
Can you change hover and click image to the following
![Click_on_state_button](https://github.com/ApericotStudio/Poltergeist/assets/29505193/840d8e6a-9d68-47fc-988f-7da2dd39cb2b)
![Hover_state_button](https://github.com/ApericotStudio/Poltergeist/assets/29505193/d64b6e6f-f30b-48c7-bc01-88a818ce0e86)

You can put a script on all buttons (search for buttons in scene with t:Button in searchbar):
Make a scriptable object that holds a reference to three sprites for hover, click and idle.
In the script swap out button sprite on select, on hover, on click

2024-01-18 13:45 UTC, hassanmohamed2003 commented
brown click, light hover

2024-01-18 16:05 UTC, ThijsvanDijk requested changes
Works pretty nicely overall, but a few things need fixing:
Level Select:
- [ ] Final Exam in timetable does not highlight like Assignment

Credits:
- [ ] Both selecting and clicking with controller does not work for me

Pause menu:
- [ ] Cannot close button map after opening it
- [ ] After closing an overlay in pause menu with mouse could not interact with options menu anymore

Results:
- [x] Cannot do anything on results screen

End Cutscene:
- [ ] Cannot skip

End Certificate:
- [ ] Cannot skip

2024-01-18 20:44 UTC, hassanmohamed2003 commented
> Works pretty nicely overall, but a few things need fixing: Level Select:
> 
> * [ ]  Final Exam in timetable does not highlight like Assignment
> 
> Credits:
> 
> * [ ]  Both selecting and clicking with controller does not work for me
> 
> Pause menu:
> 
> * [ ]  Cannot close button map after opening it
> * [ ]  After closing an overlay in pause menu with mouse could not interact with options menu anymore
> 
> Results:
> 
> * [ ]  Cannot do anything on results screen
> 
> End Cutscene:
> 
> * [ ]  Cannot skip
> 
> End Certificate:
> 
> * [ ]  Cannot skip

lmao a few

2024-01-25 00:00 UTC, closed without merging