Change/input rework
ApericotStudio/Poltergeist pull request #72
Opened 2023-11-16 12:21 UTC by KiwiLT

## Description
Input reworked to the new input controls, aligning with designer's input schema. Note that possessing another object when already possessing IS NOT IMPLEMENTED YET. You can try and enter possession aim mode but it will be buggy.

## Setting up testing environment
1. In the project window navigate to Project/Assets/Scenes and open the InputRework scene.
2. Press Play.

## Feature Review
#### Testing the Anxiety Meter
Criteria:

- [x] Player enters Possess Aim mode with Left Mouse Press.
- [x] Player cancels Aim mode or Throw mode with c.
- [x] Player confirms aim mode with LMB release.
- [x] Player cancels aim mode with LMB release when not selecting an object.
- [x] Player enters throw mode with RMB.
- [x] Player throws with RMB release.
- [x] Player unpossess with Q.
- [x] Player can enter Possess aim mode while possessing an object.

## ToDo
- [ ] Possessing a different object when already possessing needs to be fixed. This includes:
  - [ ] Camera should have a smooth transition
  - [ ] It should call Unpossess() first before repossessing.

## Checklist
_These checks should always be true for your pull request_
- [x] My pull request is for one story/feature.
- [x] Every individual commit in this pull request is logical.
- [x] All code, documentation, commits and player seen texts are in English.
- [x] I have deleted unused / unnecessary code.
- [x] If my edits need a change in documentation, then I have updated the documentation.
- [x] All code is in correspondence with the code conventions.

2023-11-16 17:49 UTC, hassanmohamed2003 requested changes
it works, just one minor point

2023-11-16 17:49 UTC, hassanmohamed2003 commented on Assets/Scripts/Player/AimMode.cs
>      public void ExitAimMode()
why is this function called ExitAimMode if it also does ThrowMode functionality?

2023-11-17 09:44 UTC, ThijsvanDijk approved these changes
Looks good!

2023-11-17 09:44 UTC, ThijsvanDijk commented on Assets/Scripts/Player/AimMode.cs
>      public bool aimmode;
Please start public variables with capital letter

2023-11-17 10:01 UTC, KiwiLT commented on Assets/Scripts/Player/AimMode.cs
>      public void ExitAimMode()
throw mode is a special aim mode

2023-11-17 10:02 UTC, merged