Change/possession camera
ApericotStudio/Poltergeist pull request #92
Opened 2023-11-17 13:32 UTC by KiwiLT

## Description
You can now change from possession to possession. I had to add extra camera's for a smooth transition. Also unpossess the current object when repossessing (but not with changing to the player in-between).

## Setting up testing environment
1. In the project window navigate to Project/Assets/Scenes and open the "PossessionCamera" scene.
2. Press Play.

## Feature Review
#### Aim mode offset
Criteria:
- [x] Releasing LMB when in Possess aim mode when hovering an object causes you to possess a new object.
- [x] The previous object is correctly unpossessed when repossessing.
- [x] The camera has a smooth transition.
- [x] Possession should still work correctly when repossessing, going back to player and then possessing again.

## Checklist
_These checks should always be true for your pull request_
- [x] My pull request is for one story/feature.
- [x] Every individual commit in this pull request is logical.
- [x] All code, documentation, commits and player seen texts are in English.
- [x] I have deleted unused / unnecessary code.
- [x] If my edits need a change in documentation, then I have updated the documentation.
- [x] All code is in correspondence with the code conventions.

2023-11-17 13:33 UTC, KiwiLT commented
This is a cool feature but there might be pull requests that are more urgent. Check this before reviewing.

2023-11-17 14:41 UTC, Jeroenvn requested changes
It works! but there's some things in the code that could use some adjustments

2023-11-17 14:41 UTC, Jeroenvn commented on Assets/Scripts/Possession/PossessionController.cs
> +    private void RemovePossession()
the name of the function makes it sound like it does the same thing as Unpossess()

2023-11-17 14:41 UTC, Jeroenvn commented on Assets/Scripts/Player/AimMode.cs
> +        }
This is difficult to read without context. This operation could be described in a short sentence SwapPossessionCamera or something along those lines. If you put this in a function with a name like that and call it it makes the code that much more readable.

2023-11-17 14:41 UTC, Jeroenvn commented on Assets/Scripts/Player/AimMode.cs
>          Transform pos = _possessionController.CurrentPossession.GetComponent<ClutterCamera>().CinemachineCameraTarget.transform;
Also please change the name pos to something more descriptive. pos is used for position.

2023-11-17 14:41 UTC, Jeroenvn commented on Assets/Scripts/Player/AimMode.cs
>      public void changeCameraToPossession()
Methods should be camel case

2023-11-17 14:41 UTC, Jeroenvn commented on Assets/Scripts/Player/AimMode.cs
>      public void changeCameraToPossession()
same goes for switch camera

2023-11-20 12:16 UTC, Jeroenvn approved these changes
Looks good!

2023-11-20 12:47 UTC, closed without merging